### ISSUE TITLE
ITrackableExtended<TProperty> interface

### ISSUE THREAD

**Issue by tonysneed** [TrackableEntities/trackable-entities#105]
We should create an `ITrackableExtended<TProperty>` interface in a PCL called TrackableEntities.Common.Extended, which references TrackableEntities.Common.  The interface should inherit from `ITrackable` but add a `TrackgingStateExtended` property of type `<TPropertyType>`.

This provides an extensibility hook for supplying additional state metadata, which can be utilized for extending the `DbContext.ApplyChanges` method in the server library.  An example would be for specifying that entities on one side of a M-M relation are to be created rather than merely added to the relationship.

This issue was first proposed in #102 and discussed in this [comment](https://github.com/TrackableEntities/trackable-entities/issues/102#issuecomment-171965676).

**Comment by luboshl** [comment]
Ok :smile: What about namespace? `TrackableEntities.Common.Extended` or just `TrackableEntities.Extended` as `TrackableEntities` namespace for `ITrackable`?

And what exactly does "PCL" mean? I understand it as VS project, but what is that abbreviation for?

**Comment by tonysneed** [comment]
The namespace should be the same as the project: TrackableEntities.Common.Extended

PCL stands for Portable Class Library.

**Comment by tonysneed** [comment]
Sorry, I think we made an exception to this namespace rule for ITrackable, so we should now use: TrackableEntities.Extended

**Comment by luboshl** [comment]
@tonysneed, this issue can be closed.
