### ISSUE TITLE
Different targets of Portable Libraries

### ISSUE THREAD

**Issue by luboshl** [TrackableEntities/trackable-entities#116]
Warning after build:

*Unable to add a reference to project 'TrackableEntities.Common'. The targets of Portable Library project 'TrackableEntities.Common' are not the same or compatible with the targets of the current Portable Library project.*

*A Portable Library project's targets can be changed via the Library tab in the project's properties.	TrackableEntities.Client*

![image](https://cloud.githubusercontent.com/assets/4955190/12497608/13577d5a-c09d-11e5-85d0-1a8e97a4ee9c.png)

TrackableEntities.Client:
![image](https://cloud.githubusercontent.com/assets/4955190/12497645/5d6a700a-c09d-11e5-81f5-2619b18927e1.png)

TrackableEntities.Common:
![image](https://cloud.githubusercontent.com/assets/4955190/12497638/5439efd8-c09d-11e5-80e9-d34f7bdf2085.png)

**Comment by tonysneed** [comment]
I've seen this warning, and we can ignore it.  It's as a result of the support for ASP.NET Core 5.0 in VS 2015.

**Comment by luboshl** [comment]
Ok
