### ISSUE TITLE
1-M, M-M problems

### ISSUE THREAD

**Issue by coram** [TrackableEntities/trackable-entities#119]
Dear Tony!

I think there are some problem with the 1-M, M-M relationships handling. The problem occurs in your sample application too (WebApiSample.Mvvm). So you can repeat the problem with the following steps:
- load the customers
- choose one customer order to modify
- add an orderdetail and save. At this point everything is good, the new orderdetail saved.
- now modifiy the same order (without reload datas)
- add an another orderdetail, and save
- now you will get an exception (all detail is in the changetracking, the unchanged too, and the framework will try to save them as new entity)
The problem is the same, if you try to delete details, or simply modify it more times. So you can edit the details after the fist load only once.

Have you got any idea? Thanks, Daniel

**Comment by tonysneed** [comment]
Thanks for reporting and for the steps you took. What is the error message?

**Comment by coram** [comment]
How i see, the problem is, that first time the changed order (after ChangeTracker.GetChanges().SingleOrDefault()) contains only the modified orderdetail, with modified state. But next time the order->orderdetails contains all detail (i modified only one detail), 2 of them with unchanged state and the modified with modified state, and the framework will try to save them as new entity.
The error message was:  Attaching an entity of type .....failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values.

**Comment by tonysneed** [comment]
Did you figure it out then?

**Comment by coram** [comment]
Sorry, but i didn't find the problem. I tried to debug it, but it's too complex for me.

**Comment by tonysneed** [comment]
No problem, I'll be glad to have a look.

**Comment by tonysneed** [comment]
I am still investigating this.  Thanks for your patience.

**Comment by tonysneed** [comment]
This issue had to do with the interaction between the change tracker and this specific implementation of IEditableObject, which clones an entity when editing it.  I added code to work around the problem by setting the Customer property to null after calling GetChanges.  This work here because we are not updating an order's customer.

@coram In order to get the updated samples, you can [download](https://github.com/TrackableEntities/trackable-entities/archive/develop.zip) the updated repo .
