### ISSUE TITLE
Handle Business Logic through a Single Pipeline per Entity

### ISSUE THREAD

**Issue by boosterch** [TrackableEntities/trackable-entities#121]
Hi Tony,

Long time ago, but still working with Trackable Entities for some projects. ☺ 
I have a question about how to integrate my Business Layer with TE.

What I would like to have is a Single Pipeline per Entity for Create, Add, Update, Delete operations.
WCF Ria (Silverlight) had this handled through the LinqToEntitiesDomainService.
When inserting an Order with 3 OrderLines from the client the process is:
- 1x Call to InsertOrder(...)
- 3x Call to InsertOrderLine(...)
--> PersistChangeSet (IDbContext.SaveChanges)

Now when working with Trackable Entities and inserting an Order with 3 OrderLines the process is:
 - OrderController.PostOrder(Order order)
 - _dbContext.ApplyChanges(order);
 - _dbContext.SaveChangesAsync();

What I would like to do is Handle Some Business Logic when adding an OrderLine.
For Example check if the product is available, or check for specific discount on the product.

Is there a way to get notified when the Entity State through ApplyChanges has changed.
I could not find any way in Entity Framework to get notified of a changed Entity Maybe I could use the solution according to the issue / pr "Added intenceptors supportting fluent API and concrete StateChangeInterceptor"
So I could build some kind of BusinessLogicInterceptor?

Maybe this is out of scope for Trackable Entities.

Hope you have any suggestions. 

Thanks in advance. Regards, Corné

**Comment by tonysneed** [comment]
Hello Corné,

Yes, this is something you can do with interceptors.  I think you would want to create your own interceptor to perform your business logic.  See [these tests](../blob/develop/Source/Tests/TrackableEntities.EF.5.Tests/StateInterceptorTests.cs) for how to use the API.  But you may find it easier to just use the StateChangeInterceptor.  See [these tests](../blob/develop/Source/Tests/TrackableEntities.EF.5.Tests/StateChangeInterceptorTests.cs) for that API.

Cheers,
Tony

**Comment by boosterch** [comment]
Hi Tony,

Thank you for your quick response.
I will make my own interceptor "BusinessLogicInterceptor" and hook that to my BusinessLogicFactory.

Thanks,
Corné
