### ISSUE TITLE
Deleting one-to-one relationships

### ISSUE THREAD

**Issue by cyrusdowney** [TrackableEntities/trackable-entities#122]
So we are having an issue (we might have gone about something the wrong way), but I was able to recreate the issue in a failing test (below).  The error is 

> The DELETE statement conflicted with the REFERENCE constraint "our FK name here". The conflict occurred in database "our database name here", table "our table name here", column 'our column name here'.
> The statement has been terminated.

The right hand side of the one to one relationship is being set to null on the changes returned from GetChanges, when deleting the left hand side of the relationship.  It is causing an issue with our save.  Our children deletes are working just fine in other areas of our system.

So I don't know if we are miss-using the concepts, or should go about our situation differently.  I'm open to ideas.  I did play around with the cloning code, but using EntityNavigationPropertyResolver only in the clone method, broke several other tests.

`[Fact]
public void One_To_One_Deleted_Customer_Returning_Empty_Settings()
{
	// Arrange
	var database = new MockNorthwind();
	var customer = database.Customers[0];

	customer.CustomerSetting = new CustomerSetting { CustomerId = "ALFKI", Setting = "TESTSETTING" };
	//making sure the relationship is set up both ways
	customer.CustomerSetting.Customer = customer;

	var changeTracker = new ChangeTrackingCollection<Customer>(customer);

	customer.TrackingState = TrackingState.Deleted;
	customer.CustomerSetting.TrackingState = TrackingState.Deleted;
	database.Customers.Remove(customer);

	//cloning objects works just fine under EntityNavigationPropertyResolver
	Customer closeTest = customer.Clone();
	Assert.NotNull(closeTest.CustomerSetting);

	CustomerSetting cloneTest2 = customer.CustomerSetting.Clone();
	Assert.NotNull(cloneTest2.Customer);

	// Act
	var changes = changeTracker.GetChanges();
	
	// Assert
	Assert.NotEmpty(changes);
	Assert.Equal(TrackingState.Deleted, changes[0].TrackingState);
	Assert.NotNull(changes[0].CustomerSetting);
}`

**Comment by tonysneed** [comment]
@cyrusdowney,

In order to delete entities from a 1-1 relation, you need to remove the customer from `changeTracker`, not from `database.Customers`.  This will mark Customer as Deleted, which should be sufficient to delete both Customer and CustomerSetting.  When you call `dbContext.ApplyChanges`, it will then set EntityState on both Customer and CustomerSetting to Deleted.  Calling `dbContext.SaveChanges` should then delete both the customer and its setting.  Can you try that?

Cheers,
Tony

**Comment by cyrusdowney** [comment]
Actually that is what we are doing, I've pasted code from our project below.  I just created the test incorrectly.  I've updated the test below as well.  I tested our code, with the one to one relationship fully populated and the delete flows through EF correclty, so I know that it is not a cascade\EF config issue.  

in other works, if the right side of the one to one relationship is populated, the delete works fine.  Let me know if you want me to try anything else.

Our project:

` ChangeTrackingCollection<Counterparty> allCounterparties = View.Counterparties;

                        // Get the changes.
                        ChangeTrackingCollection<Counterparty> changes = allCounterparties.GetChanges();

                        if (changes.Count > 0)
                        {
                            // Save changes and merge the changes into the original list.
                            CounterpartyService.SaveData(ref changes);
                            allCounterparties.MergeChanges(changes.ToArray());

                            View.Counterparties = allCounterparties;
                        }

                        View.Sort<Counterparty>();
                        View.IsDirty = false;`


Updated test:
`        [Fact]
        public void One_To_One_Deleted_Customer_Returning_Null_Settings()
        {
            // Arrange
            var database = new MockNorthwind();
            var customer = database.Customers[0];

            customer.CustomerSetting = new CustomerSetting { CustomerId = "ALFKI", Setting = "TESTSETTING" };
            //making sure the relationship is set up both ways
            customer.CustomerSetting.Customer = customer;

            var changeTracker = new ChangeTrackingCollection<Customer>(customer);

            customer.TrackingState = TrackingState.Deleted;
            customer.CustomerSetting.TrackingState = TrackingState.Deleted;
            
            //removing the item
            changeTracker.Remove(customer);

            //cloning objects works just fine under EntityNavigationPropertyResolver
            Customer closeTest = customer.Clone();
            Assert.NotNull(closeTest.CustomerSetting);

            CustomerSetting cloneTest2 = customer.CustomerSetting.Clone();
            Assert.NotNull(cloneTest2.Customer);

            // Act
            var changes = changeTracker.GetChanges();
            
            // Assert
            Assert.NotEmpty(changes);
            Assert.Equal(TrackingState.Deleted, changes[0].TrackingState);
            Assert.NotNull(changes[0].CustomerSetting);
        }`

**Comment by tonysneed** [comment]
@cyrusdowney, Thanks for the clarification.  I see the problem now.  Removing a customer marks it as deleted, but it sets the CustomerSetting property to null.  Rather than setting it to null, CustomerSetting should be set to Unchanged or Deleted, so that calling `ApplyChanges` on the server-side will set the `EntityState` of both Customer and CustomerSetting to Deleted.

I'll mark this as a bug, so that we can fix it.  In the meantime, a workaround would be for you to explicitly mark `TrackingState` of both Customer and CustomerSetting as `Deleted`, **instead** of calling `changeTracker.Remove(customer)`.  That should result in deleting both the customer and setting.

Cheers,
Tony

**Comment by cyrusdowney** [comment]
Thanks Tony.  I did some spelunking through the  "GetChanges" changes code.  The issue appears to happen in the "TrackableExtensions.CloneObject" method.  From what I could tell, the "CloneChangesHelper.GetChanges" works just fine.  But the object is not being copied over during "CloneObject's" deepcopy.  That is why I included the clone testing lines\asserts.  

It works fine when I call Cone myself, but when track changes calls "CloneObject", a "CloneChangesHelper" is being passed into the CloneObject method.  So the "DefaultContractResolver" is being used instead of the "EntityNavigationPropertyResolver".  Of course, when I updated "CloneObject" to use "EntityNavigationPropertyResolver" only, my test started working, but like 18 others failed.

hth,
Cyrus

**Comment by tonysneed** [comment]
@azabluda, Would you possibly have time to take a look at `CloneChangesHelper`?  TIA. :smile:

**Comment by cyrusdowney** [comment]
@tonysneed Tony, I tried the workaround, but in our case it didn't work.  Our list is bound to a grid, where the user can make multiple changes (adds, updates, deletes) and then saves all the changes at once.  Just setting the `TrackingState` on both of our entries doesn't remove the item from the grid, until changes are saved.

I altered the `One_To_One_Deleted_Customer_Returning_Null_Settings` test, and commented out the part where the customer was being removed from the change tracker and the Settings object was _still_ null, in the changes result.  

One workaround I can think of in our case, is to just store deleted changes separately, and then perform some additional logic to remove\send the complete one to one relationship to the server.  Can you think of anything else?

**Comment by tonysneed** [comment]
@cyrusdowney,  Yes I think your workaround should work. Clone the entities which are to be deleted, (instead of calling GetChanges), as you did in your test, set TrackingState to Deleted, then send them to your service where changes can be applied and saved.

**Comment by azabluda** [comment]
@tonysneed I looked into this issue, and the current behavior feels consistent with unit test [GetChanges_On_Existing_Order_With_Modified_Customer_With_Deleted_Territory_Should_Set_Territory_To_Null](https://github.com/TrackableEntities/trackable-entities/blame/855b489e953e76be12e8b66833e1d32899d04a86/Source/Tests/TrackableEntities.Client.Tests/ChangeTrackingCollectionWithChildrenTests.cs#L1232)

The only substantial difference between Cyrus' test and yours is that his `customer` object is `Deleted` whilst yours is `Modified`. Could you quickly explain why would you expect no `Customer.Territory` in your case? Thanks

**Comment by cyrusdowney** [comment]
@tonysneed @azabluda I just wanted to check and and see if I could help answer any questions.  I was also curious what the timeline for a fix looks like? 
We are getting ready for a beta reason of our system, and I need to know if I should go ahead and implement the fix (tracking deleted items separately for one to one relationships in out system), or wait for a fix in the main branch is in.

Thanks,
Cyrus

**Comment by tonysneed** [comment]
I can't remember entirely at this time, but it may have had something to do with Delete meaning "remove the relation" vs "delete the entity", which may not apply to 1-1 relations. So it appears that assumption was not valid - what do you think?

**Comment by azabluda** [comment]
In my (perhaps simplistic?) opinion `GetChanges` should not decide whether to include or exclude the deleted child node depending on the state of its master. Thus if a node is marked as anything besides `Unchanged`, then it should be returned. This rule is straightforward and gives more explicit control to the application code.

Please check my PR #123.

**Comment by tonysneed** [comment]
I agree! Should have a chance to look at your PR today. Thank you!

**Comment by tonysneed** [comment]
Fixed with PR #123.
