### ISSUE TITLE
Is "RejectChanges" planned for a future version?

### ISSUE THREAD

**Issue by mightyScoop** [TrackableEntities/trackable-entities#125]
Hi Tony,

in my current project i use your ChangeTrackingCollection (really good work btw.). An undo functionality is requested. Do you plan to implement a "RejectChanges" function in a future release?

Thx in advance,

Dominic

**Comment by tonysneed** [comment]
Sorry for the late response - didn't see this before.  Reject changes is possible by using a library that implements [IEditableObject](https://msdn.microsoft.com/en-us/library/system.componentmodel.ieditableobject(v=vs.110).aspx), such as Simple Mvvm Toolkit.  See this [sample](https://github.com/TrackableEntities/trackable-entities/tree/develop/Samples/VS2013/WebApiSample.Mvvm).

**Comment by tonysneed** [comment]
Closing this question as having been answered.
