### ISSUE TITLE
Changing Parent on Child Object...

### ISSUE THREAD

**Issue by blewis1975** [TrackableEntities/trackable-entities#127]
Hello,

What is the suggested way of moving a child object to a different parent in a ChangeTrackingCollection<> list? Every option I've tried gives me a referential integrity constraint when ApplyChanges() is called on a DbContext. I've tried removing the item from one list and adding it to another, but doing this causes a delete and insert. I've tried updating the parent object and/or parentid, but no luck. Any suggestions?

**Comment by blewis1975** [comment]
Hey Guys,

Any suggestions on this?

**Comment by tonysneed** [comment]
@blewis1975, thanks for the ping .. I've been submerged with teaching and speaking the past couple of weeks, and this one dropped off my radar.

Have you tried setting the Tracking property on the change tracker to false, then move the child item, before setting Tracking back to true again?

**Comment by blewis1975** [comment]
@tonysneed, thanks for the advice. That worked great! Appreciate the feedback.
