### ISSUE TITLE
GetChanges on Client throws Newtonsoft.Json.JsonSerializationException

### ISSUE THREAD

**Issue by edi0177** [TrackableEntities/trackable-entities#128]
Hello Tony and Contributors,

i am moving from TE 2.2 to current 2.5 and now facing a Problem with the current implementation of GetChanges. 

I have a WCF Webservice, which serves ma entity-objects (now all from type EntityBase) and a .net 4.5.1 Client Application which recives the entities.

The Entity-POCO's are shared between server and client as a Nuget-Package.

The Exception occurs if i recive some objects from the server and call GetChanges:

 Message:
 Could not find type 'TrackableEntities.Client.ChangeTrackingCollection`1+CloneChangesHelper+Wrapper[[My.Shared.Namespace.MyEntityObj, My.Shared.Namespace]]' in assembly 'TrackableEntities.Client, Version=2.5.0.0, Culture=neutral, PublicKeyToken=b10b51e7b9be6a2e'.

I added the Stacktrace

[stacktrace.txt](https://github.com/TrackableEntities/trackable-entities/files/210213/stacktrace.txt)

it seems that the DefaultSerializationBinder wants to find my object-Type in the Trackable Entities assembly, becouse the JSON Serializer is called from there.

So the one option i found is to derrive my own DefaultSerializationBinder like in 
http://stackoverflow.com/questions/17485955/how-to-change-the-assemby-and-the-object-type-on-the-newtonsoft-json-serializati

But is there a better option than that ?

I am using Newtonsoft JSON 6.0.8, like the dependency from the TE nuget package.

<package id="TrackableEntities.Client" version="2.5.2" targetFramework="net451" />
  <package id="TrackableEntities.Common" version="2.5.2.1" targetFramework="net451" />
 <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net451" />

Thank you for your help

Konrad

**Comment by tonysneed** [comment]
Have you updated the TE NuGet packages to their latest version?  You can do that through the NuGet package manager.

If you are still getting an error, could you provide me with a simple repro?  Just upload it to GitHub and paste the URL here.  Thanks!

**Comment by edi0177** [comment]
I updated from 2.2 to the latest version... I create a sample app for you

**Comment by tonysneed** [comment]
@edi0177, Is this still a problem for you?

**Comment by edi0177** [comment]
Hello Tony, 
sorry i forgot to provide you a sample.
I created one, but in a simple sample application the problem will not occur
The Problem still exist for me but i found a workaround for it:

Now in my Application init  i subscribe for Appdomain AssemblyResolve event and handle it for my shared entities-assembly (nuget-package)

` if (new AssemblyName(args.Name).Name == typeof(MyTrackableAssembly).Namespace)
            {
                return AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(a => a.GetName().Name == args.Name);
            }`

I see no difference between the partial binding which is used in the json serializer for assemblies which work and my (shared trackable) ones.

So i have no clue why it's not working in my solution. Maybe it could be because of i sign the assemblies (client and shared). But it should not.

But i have a few projects and it will occur in all of them, maybe because they all have the same setup

**Comment by tonysneed** [comment]
Let me know if you are eventually able to create a simple sample that reproduces the problem.  Otherwise, I can go ahead and close the issue, as you seem to have found a workaround.
