### ISSUE TITLE
Trouble with child class TrackingState

### ISSUE THREAD

**Issue by Dvornik** [TrackableEntities/trackable-entities#129]
Hi, Tony! Thank you very much for SimpleMvvmToolkit. I built application and it's fine. 
Now I'll tring to start new project with TrackableEntities.

Look at this simple sample, please:
```cs
public class Parent : EntityBase
{
    private Сhild _myChild;


    public Сhild MyChild

    {
        get { return _myChild; }
        set
        {

            if (Equals(value, _myChild)) return;
            _myChild = value;
            ChildChangeTracker = _myChild == null ? null : new ChangeTrackingCollection<Сhild> { _myChild };
            NotifyPropertyChanged();
        }
    }

    private ChangeTrackingCollection<Сhild> ChildChangeTracker { get; set; }
}

public class Сhild : EntityBase
{
    private string _name;

    public string Name
    {
        get { return _name; }
        set
        {
            _name = value;
            NotifyPropertyChanged();
        }
    }
}

public void Test()
{
    var parent = new Parent()
    {
        MyChild = new Сhild()
    };

    var changeTracker = new ChangeTrackingCollection<Parent>(parent);
    parent.MyChild.Name = "AAAAAAAAAA!!!!";

    System.Console.WriteLine(parent.MyChild.TrackingState.ToString()); // Unchanged
}
```

I spent a lot of time (my real model much more complicated), but I realized that the bag was connected with properties naming. If you rename MyChild -> Child everything work fine. But I think it's really unclear. 
And what should I do if I have two Properties with the same type but different names?

**Comment by tonysneed** [comment]
The property name shouldn't matter. Is the Tracking property on the change tracker set to true?

**Comment by Dvornik** [comment]
> Tracking property on the change tracker set to true
Yes.

**Comment by tonysneed** [comment]
Can you put your repro up on GitHub for me to take a look at?

**Comment by Dvornik** [comment]
>  Is the Tracking property on the change tracker set to true?

Sure.

I understood, what was wrong:


```
// very very simple console application
using System;
using TrackableEntities.Client;

namespace TrackableEntitiesTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Test();
            Console.ReadLine();
        }

        public static void Test()
        {
            var parent = new Parent()
            {
                MyChild = new Сhild(),
            };

            var changeTracker = new ChangeTrackingCollection<Parent>(parent);
            changeTracker.Tracking = true;
            parent.MyChild.Name = "New name";

            Console.WriteLine($"MyChild: {parent.MyChild.TrackingState.ToString()}"); // Unchanged

        }
    }

    public class Parent : EntityBase
    {
        private Сhild _myChild;

        public Сhild MyChild
        {
            get { return _myChild; }
            set
            {

                if (Equals(value, _myChild)) return;
                _myChild = value;
                ChildChangeTracker = _myChild == null ? null : new ChangeTrackingCollection<Сhild> {_myChild};
                NotifyPropertyChanged();
            }
        }

        private ChangeTrackingCollection<Сhild> ChildChangeTracker { get; set; } //  This name should be MyChildChangeTracker!
    }

    public class Сhild : EntityBase
    {
        private string _name;

        public string Name
        {
            get { return _name; }
            set
            {
                _name = value;
                NotifyPropertyChanged();
            }
        }
    }
}
```

Output: `MyChild: Unchanged`
But after renaming ChildChangeTracker to MyChildChangeTracker output is: `MyChild: Modified`as it should be.
I think ChangeTracker property name matters, doesn't it?

**Comment by tonysneed** [comment]
Now I see what name you're talking about: the MyChild property of the Parent class.  My default there is a convention that the change tracker name must match.  But it is possible to use a different name .. Another team member worked on that, so I can't recall the mechanism off the top of my head.

@azabluda, Could you paste a snippet to illustrate?

**Comment by Dvornik** [comment]
>  My default there is a convention that the change tracker name must match.

Ok, now it's clear. It's ok, it's a good convention. I had this issue because I tried to build application from scratch without codegeneration (I use code first without legacy db). Is not usual TE case. 
Thank you!
