### ISSUE TITLE
After removing an item that has Added state it goes to the _deleted internal collection with state Unchanged.

### ISSUE THREAD

**Issue by gtas-verisk** [TrackableEntities/trackable-entities#132]
So I have an object graph.

> MainObj -> TrackingCollection1<Obj1>
>                -> TrackingCollection2<Obj2>
>                -> TrackingCollection3<Obj3>

Say I create an instance Instance1 and has TrackingState = Unchanged, modify some properties, now TrackingState = Modified, then add it to TrackingCollection1<Obj1>.Add(Instance1), now TrackingState = Added, then modify a property, TrackingState = Modified again, now TrackingCollection1<Obj1>.Remove(Instance1) it is added to the internal collection with TrackingState = Deleted, all good.

Now in another scenario.  I create an instance Instance1 and has TrackingState = Unchanged, modify some properties, now TrackingState = Modified, then add it to TrackingCollection1<Obj1>.Add(Instance1), now TrackingState = Added, I do not modify again any properties and immediately remove it, TrackingCollection1<Obj1>.Remove(Instance1) it is added to the internal collection with TrackingState = Unchanged, this has an effect when calling GetChanges() that it takes the "Unchanged" item from the internal _deleted collection back to the TrackingCollection1<Obj1>, check the extension method below.

```
public static IEnumerable<T> GetDeletedEntities<T>(this ChangeTrackingCollection<T> list, IMainThreadDispatcherService dispatcherService) where T : class, ITrackable, INotifyPropertyChanged
        {
            IList<T> dtos = new List<T>();
            if (list.Any())
            {
                dispatcherService.RequestMainThreadAction(() =>
                {
                    dtos = list.GetChanges().Where(p => p.TrackingState == TrackingState.Deleted).ToList(); // Here the Unchanged item goes back to the ChangeTrackingCollection<T> list.
                });
            }
            return dtos;
        }
```

How to avoid this effect?

Update:

I see here, https://github.com/TrackableEntities/trackable-entities/blob/develop/Source/TrackableEntities.Client/ChangeTrackingCollection.cs#L256 that you have a try/finally code but you RemoveRestoredDeletes only in the finally block, but in the try block you return, I think the finally block is never invoked unless an exception, is this the desired functionality?

**Comment by tonysneed** [comment]
@gtas-verisk, Thanks for filing the issue.

I think removing an added item should not place it in the internal _deleted collection.

Are you familiar with using Git and GitHub?  If so, I'm wondering if you might be able to fork the repository, create a branch, then create a failing test.  You could then publish the branch and create a pull request which contains the failing test.  That would be ideal.

If on the other hand you're not GitHub savvy, you could try to create a failing test and simply paste the code in this issue.  Then I would create the pull request on my end.

**Comment by MarcDrexler** [comment]
@tonysneed 
I am facing the same issue as mentioned by @gtas-verisk.

I have created a pull request which contains a failing test. (sorry, I forgot to create a new branch before).

**Comment by tonysneed** [comment]
Thanks @MarcDrexler for PR #136.  I will have a look.

**Comment by tonysneed** [comment]
@gtas-verisk, @MarcDrexler: I fixed this issue with PR #137, which I've merged into the develop branch.  I will create a new release - v2.5.5 - which will include the fix and a new version of the client NuGet package.

**Comment by tonysneed** [comment]
Included the fix in [release 2.5.5](https://github.com/TrackableEntities/trackable-entities/releases/tag/v2.5.5). Published NuGet package: [TrackableEntities.Client v2.5.5](https://www.nuget.org/packages/TrackableEntities.Client/2.5.5).

**Comment by MarcDrexler** [comment]
Thank you @tonysneed for fixing it so fast! 🚀 I'm excited 😆

**Comment by tonysneed** [comment]
:smile:

**Comment by gtas-verisk** [comment]
@tonysneed Thanks for taking care of this and @MarcDrexler I appreciate finding the time to create a failed test and push this for a fix.

**Comment by tonysneed** [comment]
Glad to be of service!
