### ISSUE TITLE
Cannot find DbContext if Context doesn't inherit from DbContext directly.

### ISSUE THREAD

**Issue by kourosko** [TrackableEntities/trackable-entities#133]
Sorry for my English.
First of all Great, really great job. I strongly believe that the way you do things is the proper way.
I haven't fully tested but I'm implementing it in a new project.
I'll explain the problem.
I have a class BioContext that inherits from BaseContext.
BaseContext inherits from dbContext.
When i go to add new web api controller i don't get BioContext. 

I've read you code and found the problem in TrackableEntities.ItemWizard project in class ModelReflectionHelper.cs :

`private static bool InheritsFrom(this Type type, Type comparedType)
        {
            // Test for null
            if (type == null || comparedType == null) return false;

            // Test for interfaces
            if (comparedType.IsInterface)
            {
                return type.GetInterfaces().Any(t => t.FullName == comparedType.FullName);
            }

            // Test for base class
            return type.BaseType != null &&
                type.BaseType.FullName == comparedType.FullName;
        }` 
to=>
 private static bool InheritsFrom(this Type type, Type comparedType)
      `{
            // Test for null
            if (type == null || comparedType == null) return false;

            // Test for interfaces
            if (comparedType.IsInterface)
            {
                return type.GetInterfaces().Any(t => t.FullName == comparedType.FullName);
            }

            // Test for base class
            return (type == comparedType||type.IsSubclassOf(comparedType));
        }`

**Comment by tonysneed** [comment]
Thanks so much for opening this issue. Would you be able to submit a pull request with your proposed fix?

**Comment by kourosko** [comment]
Problem fixed.
