### ISSUE TITLE
ChangeTrackingCollection is modified when calling GetChanges

### ISSUE THREAD

**Issue by MarcDrexler** [TrackableEntities/trackable-entities#139]
Following Scenario:
An employee has 3 territories in its territory collection and I remove all of them.
The territory collection count is zero.

After calling GetChanges, the territory collection is not empty anymore and shows 1 territory with tracking state "Deleted". 

The collection should not be modified when calling GetChanges.

See failing test in #138

**Comment by tonysneed** [comment]
Have you updated the Nuget package to latest version?

**Comment by tonysneed** [comment]
I will take a look

**Comment by MarcDrexler** [comment]
I forked the latest version.

**Comment by tonysneed** [comment]
Fixed by PR #140.

**Comment by tonysneed** [comment]
@MarcDrexler Thanks for catching this one.  Let me know if you find anything else.

**Comment by MarcDrexler** [comment]
@tonysneed I am migrating an existing application to trackable entitites and I am still at the beginning. I will let you know as soon as I find something :)

I have two more questions:
- How do you decide when to create new NuGet packages?
- If you want to create stable packages only, I think it would be useful to have pre-release packages for each new version. This would help me a lot, otherwise I need to get the latest source code, change references, etc..
- Is this process automated in here?

**Comment by tonysneed** [comment]
Every commit that is pushed to the develop branch triggers a build of new packages on MyGet, so you don't have to wait for an official release. See this post for info: https://www.google.sk/amp/s/blog.tonysneed.com/2014/10/25/myget-continuous-integration-for-the-rest-of-us/amp/

**Comment by tonysneed** [comment]
Give me a few minutes to update the MyGet feed settings, and I'll post the info here that you will need to use it.

**Comment by MarcDrexler** [comment]
Ok, thanks 👍

**Comment by tonysneed** [comment]
Here is the info you need:

### VS 2015 Package Manager Settings

*Add a package source:* **TE-MyGet**
https://www.myget.org/F/trackable-entities-ci/api/v3/index.json

*Execute from Package Manager Console:*
- Select TE-MyGet as the package source

```
Install-Package TrackableEntities.Client -pre
```
