### ISSUE TITLE
Updating NuGet Packages

### ISSUE THREAD

**Issue by tonysneed** [TrackableEntities/trackable-entities#142]
By @MarcDrexler: I am migrating an existing application to trackable entitites and I am still at the beginning. I will let you know as soon as I find something :)

I have two more questions:

How do you decide when to create new NuGet packages?
If you want to create stable packages only, I think it would be useful to have pre-release packages for each new version. This would help me a lot, otherwise I need to get the latest source code, change references, etc..
Is this process automated in here?

**Comment by tonysneed** [comment]
Every commit that is pushed to the develop branch triggers a build of new packages on MyGet, so you don't have to wait for an official release. See this post for info: https://www.google.sk/amp/s/blog.tonysneed.com/2014/10/25/myget-continuous-integration-for-the-rest-of-us/amp/

**Comment by tonysneed** [comment]
Here is the info you need:

### VS 2015 Package Manager Settings

*Add a package source:* **TE-MyGet**
https://www.myget.org/F/trackable-entities-ci/api/v3/index.json

*Execute from Package Manager Console:*
- Select TE-MyGet as the package source

```
Install-Package TrackableEntities.Client -pre
```

**Comment by tonysneed** [comment]
@MarcDrexler:

Created a separate issue from your question in #139.

Did you try this?  Did it work for you?

**Comment by MarcDrexler** [comment]
@tonysneed It works. Thanks!
