### ISSUE TITLE
Removing and adding entity should restore to its original state

### ISSUE THREAD

**Issue by tonysneed** [TrackableEntities/trackable-entities#145]
This issue is related to PR #144: Failing Test: Removing and adding entity should not mark it as Added or Removed.

We currently don't support multi-action scenarios like this.  While we do support simple state transitions, it would require a whole other level of state management to handle scenarios where we need to know the prior state in order to set the current state when adding or removing entities.

In these cases, it is best for the user of the change tracker to set entity state to what is should be.  This can be done manually: `entity.TrackingState = TrackingState.Unchanged` (or Modified, etc).

I'm willing to entertain a proposed implementation of multi-state transitions, but it could require substantial effort and a great deal of testing.

**Comment by MarcDrexler** [comment]
I see.. I will implement a workaround in my application where I will compare the original states with the state in the change tracker. And if necessary, I will set the state what it should be like you said.

As soon as I have more time, I will try to dig deeper in your implementation. Maybe I can add this functionality. On my side I need to have the necessary unit tests anyway.

**Comment by tonysneed** [comment]
Sounds good .. Let me know if you are able to provide an implementation.  When you get to that point, consider using the [State design pattern](http://www.dofactory.com/net/state-design-pattern).

**Comment by MarcDrexler** [comment]
Alright, I will let you know.

**Comment by MarcDrexler** [comment]
If you already have the structure of the implementation which is needed in your head (at least it sounds like that 😛 ), then it would be much more efficient if you just code it in a new branch. I will do the testing 😄

**Comment by tonysneed** [comment]
The best would be to write the tests first, ala TDD. :) xUnit Theory would help by allowing you to parameterize tests, but you would need to cover several different state transitions for each relationship type: 1-1, M-1, 1-M and M-M.

As for implementation, I am busy with another project until mid-October, but I might be able to work on it then.
