### ISSUE TITLE
Combining T4 templates?

### ISSUE THREAD

**Issue by Blastnsmash** [TrackableEntities/trackable-entities#152]
What is the strategy suggested if you generate your models with an existing T4 template but you want to incorporate your tooling? How do you combine the T4 templates? 

I don't have much experience with IL weaving but have you considered?

:)

**Comment by tonysneed** [comment]
I'm not clear on your question .. can you provide an example?

**Comment by Blastnsmash** [comment]
There are other libraries that want to use T4 templating. For example, a Authorization library will use T4 template to inject code into the getter and setter methods of an entity. So as time progresses when you update your T4 template and they update their T4 template how do we seamlessly merge the changes from multiple frameworks?

I'm investigating this outside of this thread.

**Comment by tonysneed** [comment]
Most tooling based on T4 will generate classes from scratch.  TE does not have its own T4 tooling, but rather relies on generators written by the EF team, which scaffold classes based on a database schema.

The way I would suggest reconciling classes generated by different tools is to leverage *partial classes*, which are produced by most T4 tools.  If different T4 tools generate different partial class files, those files will be merged by the C# compiler.  Generating different files prevents tools from stepping on each other.  It also allows you to extend generated classes by creating your own partial classes, where you can place code that will not be replaced by the code generator.

**Comment by Blastnsmash** [comment]
Thanks for your insight. 

I will be researching this issue further, if I have more to contribute I'll add it here.
