### ISSUE TITLE
.netstandard compatability for Trackable Entities Client 

### ISSUE THREAD

**Issue by Blastnsmash** [TrackableEntities/trackable-entities#153]
Would it be possible to update the Trackable Entities client to be compatible with .netstandard?

https://docs.microsoft.com/en-us/nuget/schema/target-frameworks

> PCLs are not recommended
> + 
> Although PCLs are supported, package authors should support netstandard instead. The .NET Platform Standard is an evolution of PCLs and represents binary portability across platforms using a single moniker that isn't tied to a static like like portable-a+b+c monikers.

**Comment by tonysneed** [comment]
This is where I am working on the version of Trackable Entities for .NET Core, which is based on Net Standard: https://github.com/TrackableEntities/TrackableEntities.Core

I plan on releasing this version when VS 2017 RTM ships in May, which will finalize the MS Build-based tooling.

I also plan to release a version of TE for .NET Core 2, when Entity Framework Core will mature and support features needed for TE to work the same way as it did for EF 6.x.

**Comment by Blastnsmash** [comment]
Keep up the good work. :)
