### ISSUE TITLE
(Question) Implementing Optimistic Concurrency

### ISSUE THREAD

**Issue by Blastnsmash** [TrackableEntities/trackable-entities#155]
I am wanting to implement Optimistic Concurrency, for example, changing the Freight field on an order SQL would look like:
UPDATE Orders
   SET Freight = @Freight
 WHERE OrderID = @OrderID AND Freight = @OriginalFreightValue

The question is - is there anything in your framework that records the original value. ModifiedProperties does have a string list of modified properties but there is no associated value? Possible to change modifiedproperties to Collection<string,object>?

**Comment by tonysneed** [comment]
For optimistic concurrency you should add a rowversion column to your table and entity.  The data type in the database would be timestamp and then in your EF model you would designate it as a concurrency token.  This approach is described [here](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/handling-concurrency-with-the-entity-framework-in-an-asp-net-mvc-application) and [here](https://msdn.microsoft.com/en-us/library/jj592904(v=vs.113).aspx), and it is preferable to retaining original values for various fields.  When a conflict takes place among multiple users updating the same row at the same time, then a concurrency exception is generated in which the conflicting values are present.  You can apply whatever logic you like to resolve the conflict.

Does this help address your question?

**Comment by Blastnsmash** [comment]
The particular scenario I'm thinking of doesn't have anything to do with multi-user concurrency but a way to prevent a client from bypassing business rules. In my scenario you need to either fetch values from db and check them or you could rely on the original values from the client if you append concurrency checks for the original values (falsifying the original value would result in 0 rows updated). I've had an issue where an employee was able to bypass business rules by simply changing the original value that was on the client, the server used the original value field for validation instead of checking what the actual DB values were. Think of the situation where an update is allowed to happen on a Property  if the given Property didn't have a particular value.

If your framework doesn't have the original values that are passed, they can be checked if necessary by hitting the DB. It's a performance trade off - added network load or DB query time.

**Comment by tonysneed** [comment]
Sorry I wasn't able to respond earlier .. I am currently on vacation and have intermittent access to Internet.

I am trying to understand your question better.  You say your scenario does not have anything to do with multi-user concurrency, but then state:

> In my scenario you need to either fetch values from db and check them or you could rely on the original values from the client if you append concurrency checks for the original values (falsifying the original value would result in 0 rows updated).

This is exactly how EF allows you to manage multi-user concurrency.  But it relieves you from having to check original values.  The only way the concurrency token can change is if any of the original values has changed, which results in zero rows updated and a concurrency exception thrown by EF.  Then you can obtain values from the database present in the concurrency exception.

However, if you have a scenario where you need to use the values originally retrieved by the user from the database, then your best bet is to add a property bag to your entity to store the original values.  You could store them as a set of key-value pairs, or even as a JSON blob or something like that.

Cheers,
Tony

**Comment by tonysneed** [comment]
Closing this issue since it appears the question has been answered.
