### ISSUE TITLE
When is TE Client Version 2.5.6 planned

### ISSUE THREAD

**Issue by edi0177** [TrackableEntities/trackable-entities#158]
fixes from #141 #143 affecting my Projects too.
These are in since Sep`16
Would be nice to use it in production.
thank you

**Comment by weitzhandler** [comment]
Looks like it's pretty close.
According to the [2.5.6 Milestone](https://github.com/TrackableEntities/trackable-entities/milestone/6), there are few issues left, some of which have already been PRed and awaiting review and merge.
Hopefully @tonysneed gets some spare time for some maintenance...

Look at #170, #184 and #185.

**Comment by tonysneed** [comment]
I plan to spend an hour looking at these this morning my time.

**Comment by tonysneed** [comment]
Released 2.5.6 a while ago, so closing this.
