### ISSUE TITLE
NotifyPropertyChanged

### ISSUE THREAD

**Issue by weitzhandler** [TrackableEntities/trackable-entities#161]
@tonysneed 
Please include another overload that allows raising the `PropertyChanged` event in `EntityBase`. Currently only a lambda expression is accepted, allowing no direct way to raise property change by string from sub classes.

Besides, there is also the `CallerMemberNameAttribute` that can be solved this way. Will you accept a PR?

Temporary workaround: reflection 😢 

    protected void RaisePropertyChanged([CallerMemberName] string propertyName = null)
    {
      var eventArgs = new PropertyChangedEventArgs(propertyName);
      var type = GetType();
      var inpcDelegate = 
        (MulticastDelegate)type.GetRuntimeField(nameof(PropertyChanged)).GetValue(this);
      if (inpcDelegate != null)
        foreach (var handler in inpcDelegate.GetInvocationList())
          handler.GetMethodInfo().Invoke(handler.Target, new object[] { this, eventArgs });
    }

**Comment by tonysneed** [comment]
Hi!

The .NET 4.5 TE library uses that attribute.

I'll check on a hook for raising the PC event in EntityBase. I thought I had one there, but don't remember. :)

Yes, PR's are welcome! First fork the repo, then create a branch, then create the PR.

Thanks,
Tony

**Comment by weitzhandler** [comment]
> The .NET 4.5 TE library uses that attribute.

I'm on the PCL client (Xamarin).
<hr/>

>Yes, PR's are welcome! First fork the repo, then create a branch, then create the PR.

Sure, I'm not an animal...

**Comment by weitzhandler** [comment]
Actually the workaround I mentioned above doesn't work, because UWP doesn't allow accessing private members!

Hiding (shadowing) the base event handler won't allow us raising the event handler either.
The only stupid painfully solution that works is constructing a LINQ expression from string.
Here's my code:

    protected void NotifyPropertyChanged([CallerMemberName] string propertyName = null)
    {
      var propertyType = typeof(AppEntityBase).GetProperty(propertyName).PropertyType;
      var constant = Expression.Constant(this);
      var property = Expression.Property(constant, propertyName);

      var expression = typeof(Expression);
      var lambda = expression
        .GetTypeInfo()
        .DeclaredMethods
        .Single(mi =>
          mi.Name == nameof(Expression.Lambda)
          && mi.IsGenericMethod
          && mi.GetParameters()
            .Select(pi => pi.ParameterType)
            .SequenceEqual(new[]
            {
              typeof(Expression),
              typeof(string),
              typeof(IEnumerable<ParameterExpression>)
            }));

      var func = typeof(Func<>).MakeGenericType(propertyType);
      lambda = lambda.MakeGenericMethod(func);
      var propertyLambda =
        lambda.Invoke(null, new object[]
        {
          property,
          default(string),
          Enumerable.Empty<ParameterExpression>()
        });
      var method = typeof(EntityBase).GetTypeInfo().DeclaredMethods.Single(mi => mi.Name == nameof(NotifyPropertyChanged) && mi.IsGenericMethod);
      method = method.MakeGenericMethod(propertyType);
      method.Invoke(this, new[] { propertyLambda });
    }

I hope this issue is addressed soon because this is ugly and slow.

**Comment by weitzhandler** [comment]
Actually the workaround I mentioned above doesn't work, because UWP doesn't allow accessing private members!

Hiding (shadowing) the base event handler won't allow us raising the event handler either.
The only stupid painfully solution that works is constructing a LINQ expression from string.
Here's my code:

    protected void NotifyPropertyChanged([CallerMemberName] string propertyName = null)
    {
      var propertyType = typeof(AppEntityBase)
        .GetTypeInfo()
        .DeclaredProperties
        .Where(pi => pi.Name == propertyName)
        .Select(pi => pi.PropertyType)
        .Single();
      var constant = Expression.Constant(this);
      var property = Expression.Property(constant, propertyName);

      var expression = typeof(Expression);
      var lambda = expression
        .GetTypeInfo()
        .DeclaredMethods
        .Single(mi =>
          mi.Name == nameof(Expression.Lambda)
          && mi.IsGenericMethod
          && mi.GetParameters()
            .Select(pi => pi.ParameterType)
            .SequenceEqual(new[]
            {
              typeof(Expression),
              typeof(string),
              typeof(IEnumerable<ParameterExpression>)
            }));

      var func = typeof(Func<>).MakeGenericType(propertyType);
      lambda = lambda.MakeGenericMethod(func);
      var propertyLambda =
        lambda.Invoke(null, new object[]
        {
          property,
          default(string),
          Enumerable.Empty<ParameterExpression>()
        });

      var method = typeof(EntityBase)
        .GetTypeInfo()
        .DeclaredMethods
        .Single(mi => mi.Name == nameof(NotifyPropertyChanged) && mi.IsGenericMethod);
      method = method.MakeGenericMethod(propertyType);
      method.Invoke(this, new[] { propertyLambda });
    }

I hope this issue is addressed soon because this is ugly and slow.

**Comment by weitzhandler** [comment]
Actually the workaround I mentioned above doesn't work, because UWP doesn't allow accessing private members!

Hiding (shadowing) the base event handler won't allow us raising the event handler either.
The only stupid painfully solution that works is constructing a LINQ expression from string.
Here's my code (`AppEntityBase` refers to my subclass of `EntityBase`)

    protected void NotifyPropertyChanged([CallerMemberName] string propertyName = null)
    {
      var propertyType = typeof(AppEntityBase)
        .GetTypeInfo()
        .DeclaredProperties
        .Where(pi => pi.Name == propertyName)
        .Select(pi => pi.PropertyType)
        .Single();
      var constant = Expression.Constant(this);
      var property = Expression.Property(constant, propertyName);
      var lambda = Expression.Lambda(property, Enumerable.Empty<ParameterExpression>());
      var method = typeof(EntityBase)
        .GetTypeInfo()
        .DeclaredMethods
        .Single(mi => mi.Name == nameof(NotifyPropertyChanged) && mi.IsGenericMethod);
      method = method.MakeGenericMethod(propertyType);
      method.Invoke(this, new[] { lambda });
    }

I hope this issue is addressed soon because this is ugly and slow.

**Comment by tonysneed** [comment]
Let me see if I understand. You are trying to raise PropertyChanged from entities in a UWP app that extend EntityBase, right? I'll see if I can reproduce that.

**Comment by tonysneed** [comment]
I started a chat over in Gitter .. see you there. :)

**Comment by tonysneed** [comment]
PR #164 addresses this issue.

**Comment by tonysneed** [comment]
@weitzhandler Can you please install the [beta](https://www.nuget.org/packages/TrackableEntities.Client/2.5.6-beta1) of the Client TE NuGet package? From the Package Manager Console in Visual Studio enter the following:

```
Install-Package TrackableEntities.Client -Pre
```

Then you should be able to call `NotifyPropertyChanged` from your entities.

**Comment by weitzhandler** [comment]
I updated it to the prerelease, and it's there, I'll remove my temporary hack.
Thanks for accepting my PR and addressing this issue.

**Comment by tonysneed** [comment]
@weitzhandler Happy to address the issue.  Thanks for opening it, because it allowed me to update the packages for UWP.  If the prerelease packages work alright for you, I'll update them from beta to stable.

**Comment by weitzhandler** [comment]
I haven't tested it yet, I did plug it in my project. I'll report on later.

**Comment by weitzhandler** [comment]
OK. Tested today, it compiles alright, but at runtime, I get this exception:

System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'Void TrackableEntities.Client.EntityBase.NotifyPropertyChanged(System.String)'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at MyProj.Models.Runsheet.set_Dispatchers(ICollection`1 value)
   at MyProj.Models.Runsheet..ctor() in C:\Users\username\Documents\Visual Studio 2017\Projects\MyProj\MyProj\MyProj\Models\ModelsPartial.cs:line 112

**Comment by tonysneed** [comment]
Do you have a UWP project, or something else?

**Comment by weitzhandler** [comment]
Xamarin. Only tested the UWP so far.

**Comment by tonysneed** [comment]
I'll reproduce on my end.

**Comment by tonysneed** [comment]
@weitzhandler Can you share the repro with me?

**Comment by tonysneed** [comment]
@weitzhandler Actually, no need for you to repro.  I just got Xamarin working with VS on my VM, and I can see an error installing the TE packages in a Xamarin PCL.  I think the problem is with a PCL profile mismatch, so I'm experimenting with that and will let you know when I've figured it out.

**Comment by weitzhandler** [comment]
I'm using profile 44 FYI.

**Comment by tonysneed** [comment]
I'm unable to target either PCL Profile 44 or 259. When I edit the csproj file manually, I get a message asking me to download an update to VS, but the update link re-directs to MSN.

![vs-update-req](https://user-images.githubusercontent.com/2836367/27233032-bd2b1238-527d-11e7-8c6a-d32cca9251ee.png)

If I try to target NetStandard 1.0, then the reflection code breaks.

**Comment by tonysneed** [comment]
@weitzhandler It looks like it might be best to port the client libraries to [NET Standard 2.0](https://github.com/dotnet/standard/blob/master/docs/netstandard-20/README.md), when it comes out, because that will [support the Reflection API](https://weblog.west-wind.com/posts/2016/Nov/23/NET-Standard-20-Making-Sense-of-NET-Again).  I think we are not too far from the release of v 2.0, so the wait shouldn't be too long. 😄

**Comment by weitzhandler** [comment]
Try installing VS selecting Xamarin as one of its components, then create a Xamarin project and add TrackableEntities -Pre
Otherwise, I'm gonna keep using the [solution](https://github.com/TrackableEntities/trackable-entities/issues/161#issuecomment-306748558) I mentioned earlier.

**Comment by tonysneed** [comment]
Yes I tried that. The problem is that the existing TE common library is not compatible with .NET Core (NetStandard 1.x), because it uses the reflection API. But when NetStandard 2.0 and .NET Core come out soon, they will be compatible.

**Comment by weitzhandler** [comment]
[Profile 44](https://www.danrigby.com/2014/05/14/supported-pcl-profiles-xamarin-for-visual-studio-2/) is incompatible with netstandard 2.0 but only std 1.2.
You can change the profile in the project settings. Make sure to set the appropriate .NET version (4.5.1 in this case).

I sent you a private message on Gitter, I'm begging you to read [it](https://gitter.im/weitzhandler).

**Comment by tonysneed** [comment]
Changing the profile does not seem to work in VS 2017. It says that I need to download an update, but the link is broken.

What I think I'll do is try installing VS 2015 to see if that helps.

I did reply to you on Gitter. Hopefully I can be of some help to you there.

Thanks,
Tony

**Comment by weitzhandler** [comment]
Weird.
You can try installing that missing feature from the VS2017 installer.
Anyway, meanwhile my workaround does the job, so I got more urgent [issues](https://github.com/TrackableEntities/trackable-entities/issues/165)...

**Comment by tonysneed** [comment]
I tried this also with VS 2015 and have the same experience.  The problem is not that there is a missing VS feature (I installed the Xamarin VS component), but it's that the **reflection** code in the TE Common library is not compatible with a PCL that targets Xamarin.  This should hopefully change in the future because Xamarin should be updated at some point to support NET Standard 2.0.

**Comment by weitzhandler** [comment]
That's really weird.
Do you use reflection to access private members? Reflection is supposed to work (using the new `TypeInfo` lib and `IntrospectionExtensions`, isn't it?

**Comment by tonysneed** [comment]
When I refactor the code to use TypeInfo, then a bunch of unit tests fail. Not sure why at this point, and I don't have time right now to debug it.

**Comment by weitzhandler** [comment]
Do you want me to try migrating to introspection API and PR?

**Comment by tonysneed** [comment]
That would be great. Make sure you can run all the tests. You'll need SQL Express. If you are using R#, configure it to run tests in separate AppDomains.

**Comment by tonysneed** [comment]
Solved by PR #164.
