### ISSUE TITLE
MergeChanges neglects affected entities

### ISSUE THREAD

**Issue by weitzhandler** [TrackableEntities/trackable-entities#166]
Hi,

Using the models in #165, after the entities have been returned from server, when I call `MergeChanges` on the client, the changes of the returned entities are not merged in the tracker (`ChangeTrackingCollection` instance wrapping a single `Runsheet`). See the following screenshots:

![image](https://user-images.githubusercontent.com/2716316/27269441-b3454c9a-54bf-11e7-958c-c99219872010.png)

After calling `MergeChanges` the added entities still remain `Added`:

![image](https://user-images.githubusercontent.com/2716316/27269570-b553dfe6-54c0-11e7-9c3a-660dfa6e70aa.png)

Do I have to call both `MergeChanges` and `AcceptChanges`?

**Comment by tonysneed** [comment]
I think you're looking at the wrong entity graph. You need to look at the entity that Tracker is tracking, versus the entity returned by GetChanges, which is a clone of the tracked entity and is intended for passing just the changes to a server Update method.

**Comment by weitzhandler** [comment]
I know, but after the updates have been merged into the tracker, the tracker entity still shows those entities as modified (or `Added` etc.).

**Comment by tonysneed** [comment]
Have you tried it in the WebApi sample from the TE repo?

Otherwise, provide me a GH repo that reproduces your issue. Thanks!

**Comment by weitzhandler** [comment]
Can't repro anymore, will reopen when encountering again.
