### ISSUE TITLE
Feature request: Introduce new GraphChanged event

### ISSUE THREAD

**Issue by weitzhandler** [TrackableEntities/trackable-entities#171]
Would be nice to have an event that raises when any property change or collection change occurs within the entire graph becomes dirty.

The use case of this is implementing an auto-save that is executed upon a change in the graph (probably with a timer).

What I'm using meanwhile is a timer that periodically checks for changes, but we could optimize that by running the timer only if there are changes to allow a grace period delay of finishing string input etc.

The `EventArgs` should provide data about the changed object and its parent, and the change that occurred.

**Comment by tonysneed** [comment]
What you really need is a dirty checker.  It should take a snapshot of a graph and be able to detect a change. It's out of scope really for TE, but I bet a modern MVVM framework will have it. Maybe MVVM Cross? Or maybe someone wrote a dirty checker and published to NuGet?

**Comment by weitzhandler** [comment]
The checker exists. I need an event. So if the user dreams for 20 secs the timer shouldn't have to take snapshots all of that time.

**Comment by weitzhandler** [comment]
A dirty checker is built in TE (`GetChanges().Any()`) already, but I can only figure out if the graph's dirty by having a timer that checks this every few seconds.
An event would allow for turning the save delay timer only if the user actually made it dirty, otherwise the save timer will be idle too.
A dirty count (i.e. number of total modification in the entire graph) could also help (less optimal tho), so that the continuous timer runs every few seconds, and runs a `DelaySave` method, which turns on a delay timer, that checks the dirty count. If it's the same as it was few seconds ago, trigger the actual save, otherwise allow user to make more changes before saving.

But really what we need is an event, so that when user changes text anywhere in the graph, it resets the save delay timer. Can you please point out extension points I can implement to achieve that?

**Comment by tonysneed** [comment]
I think there is an EntityChanged event, or something like that?

Also, see about HasChanges extension method.

**Comment by weitzhandler** [comment]
The `EntityChanged` event only tracks current entity.
Where should I add/remove listeners by walking through the graph?

**Comment by weitzhandler** [comment]
The `EntityChanged` event only tracks current entity.
Where should I add/remove listeners by walking through the graph?

Would you accept a PR?

**Comment by weitzhandler** [comment]
The `EntityChanged` event only tracks current entity.
Where should I add/remove listeners by walking through the graph?

Would you accept a PR?
What I'd like to do is add a property to the CTC that holds references to entire graph, then extend the `SetTracking` by adding an optional parameter that accepts the parent CTC, so that any entity added/removed anywhere (including via notify collection changed events), will be added/removed to the CTC graph property.
Adding/removing entity to the graph property will result in listening/unlistening to its `PropertyChanged` + collection properties `CollectionChanged` events.
Should I start with a failing test PR?

**Comment by tonysneed** [comment]
At one time I considered an event on CTC that would fire whenever an entity in the graph changed, or when an entity is added or removed from a CTC in the graph.  One problem is that you would need to take a snapshot of the graph and compare it with the current graph to determine if there is a difference.  What if you change a property value, and then change it back to its original value, so that the graph goes from changed back to unchanged?  If you're going to do this you have to make a clone or deep copy of the graph, which means serialization and that tends to be slow.

The other problem is managing memory leaks.  When someone subscribes to all these events, you have to make sure they unsubscribe, or you'll end up with memory leaks.  So you need to decide when to do that, which might be in IDisposable.Dispose, which isn't trivial to implement.  Or you could use a leak-proof eventing model, which again is non-trivial.

So it's a lot of work to pull this off. And I'm not sure this belongs in TE.  I [have this](https://blog.tonysneed.com/2011/07/10/validation-with-simple-mvvm-toolkit/) is my [Simple MVVM Toolkit](https://github.com/tonysneed/SimpleMvvmToolkit), and I would be surprised if it's not in other toolkits, such as [MVVM Light](http://www.mvvmlight.net/) or [MVVM Cross](https://www.mvvmcross.com).

**Comment by weitzhandler** [comment]
We don't need to determine if graph is changed, we just need an event raised whenever an entity in graph changes. Whether is changed or not, is determined by the sender's `ModifiedProperties` and `TrackingState` properties. I don't really care what was the original version I rather care about its current state.
We can subscribe and unsubscribe to events when properly handling its properties:

- Use the current subscription of `INotifyPropertyChanged` event for primitive properties.
- Subscribe to all properties exposing an `INotifyCollectionChanged` and unsubscribe from them upon instance changed.

Although maybe not so trivial, we can ensure no leaks, if we have a `PropertyChanging` behavior that cleans up garbage instances.

**Comment by tonysneed** [comment]
OK, so there is this `EntityChanged` event on the CTC.  It fires whenever `PropertyChanged` fires on an entity tracked by the CTC, as well as when an entity is added or deleted from the CTC.  There is a test for this: `EntityChanged_Event_Should_Fire_When_Items_Added_Modified_Deleted`.

To make this work as you describe, the CTC code needs to be updated to subscribe to the `EntityChanged` event on all the change trackers in the object graph.  You can code to recursively walk the graph, subscribing or unsubscribing to all the `EntityChanged` events on each CTC you find.

You can probably refactor the `SetTracking` method in `TrackableExtensions`, which already is walking the graph recursively without cycles (using `ObjectVisitationHelper`. If you both subscribe `+=` and unsubscribe `-=` to `EntityChanged` in the `SetTracking` method, then we can mostly avoid memory leaks, but the onus will be on the code using CTC to set `Tracking` to false.

You can create a PR with a failing test commit, then try updating `SetTracking`.  Sound good?

**Comment by weitzhandler** [comment]
Sounds great. Would you adopt this kind of behavior in TE?

**Comment by tonysneed** [comment]
Yes I'll accept a PR if you're able to implement it. Would you be able to do that?

**Comment by weitzhandler** [comment]
#173 
I think it should be fairly easy. Especially since we already have the `EntityChanged` event.

**Comment by weitzhandler** [comment]
#173 
I think it should be fairly easy. Especially since we already have the `EntityChanged` event.

**Comment by tonysneed** [comment]
Addressed by PR #186 Recursive EntityChanged event in ChangeTrackingCollection.
