### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by weitzhandler** [TrackableEntities/trackable-entities#187]
I've upgraded my project to .NET Standard.
Using the [`Microsoft.NETCore.Portable.Compatibility`](https://preview.nuget.org/packages/Microsoft.NETCore.Portable.Compatibility/) package, I was able to install Trackable Entities up until version `2.5.6-CI00038`.

Any particular reason why I can't get any higher version?

**Comment by tonysneed** [comment]
Are you getting build errors?

**Comment by weitzhandler** [comment]
Here are the errors I get (sorry I forgot to include them before)

>Package restore failed. Rolling back package changes for 'MyProj.Core'.  
>MSB3243	No way to resolve conflict between "System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Http, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.	MyProj.Core	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

**Comment by tonysneed** [comment]
The problem is PR #164. I had asked you to try out the beta1 packages. Did you ever do that?

Thanks,
Tony

**Comment by weitzhandler** [comment]
NuGet or MyGet? I have been using MyGet.

**Comment by tonysneed** [comment]
That was before you were using MyGet.

**Comment by weitzhandler** [comment]
OK nops, unable to install.

>Package TrackableEntities.Common 2.5.3-beta1 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package TrackableEntities.Common 2.5.3-beta1 supports: portable-net40+win8 (.NETPortable,Version=v0.0,Profile=Profile5)
One or more packages are incompatible with .NETStandard,Version=v1.4.
Package restore failed. Rolling back package changes for 'Hatzoloh.Core'.
Time Elapsed: 00:00:00.1595709

**Comment by tonysneed** [comment]
I'll have to back that PR out.
