### ISSUE TITLE
Readonly Properties must not be included in ModifiedProperties Collection

### ISSUE THREAD

**Issue by noufionline** [TrackableEntities/trackable-entities#201]
Hi Tony,

I have an entity base class which implements INotifyDataErrorInfo interface. When I modify an entity and save I noticed HasErrors property name is being added to the modified collection. Can you please help me to figure out how to avoid unwanted properties being added to this collection.

Thanks in advance.

Noufal

**Comment by tonysneed** [comment]
Yes, there’s an ExcludedProperties member you can set.

**Comment by weitzhandler** [comment]
Related: #184.

**Comment by weitzhandler** [comment]
Related: #184.

Tony, this harder than what it looks like, since the tracker takes care of an entire graph which can be large and hard to maintain properties.
Best thing would be an in-class (attributes?) or per-class ignore configuration, the the CTC picks up automatically.

**Comment by noufionline** [comment]
But adding readonly properties to modifiedProperties collection really doesn't make sense. I think Readonly properties must be excluded by default.

**Comment by tonysneed** [comment]
Going to circle back to this as soon as I have a chance.

**Comment by cbgreely** [comment]
Hi...we hit a similar problem. I have added a word doc outlining our solution. I welcome opinions!
[DoNotTrack.docx](https://github.com/TrackableEntities/trackable-entities/files/1597978/DoNotTrack.docx)

**Comment by weitzhandler** [comment]
@cbgreely
I couldn't open your document.
Would your document fit in your message? Please paste its content here.

**Comment by cbgreely** [comment]
Hmm…wonder why. Anyway I have attached it.

**Comment by tonysneed** [comment]
Looks like this was resolved.
