### ISSUE TITLE
Error on datatype DbGeography

### ISSUE THREAD

**Issue by Kanogi** [TrackableEntities/trackable-entities#222]
We are having a issue when doing a GetChanges() on a Collection that has a DbGeography property.
Do you have any solutions for it or are we doing something wrong?

This is the error we are receiving:
> Newtonsoft.Json.JsonSerializationException: 'Error getting value from 'WellKnownValue' on 'System.Data.Entity.Spatial.DbGeography'.'

**Comment by tonysneed** [comment]
GetChanges clones the object graph using Json.Net for serialization. DbGeography requires that you provide a converter. See https://stackoverflow.com/a/23794537.
