### ISSUE TITLE
adding child to existing perent forigen key issue <One 2 Many>

### ISSUE THREAD

**Issue by LeonBar** [TrackableEntities/trackable-entities#228]
I want to add a child to existing perant object:

```
var changeTracker = new ChangeTrackingCollection<ServiceCall>(serviceCall);
serviceCall.ServiceCall_Subject_Is.Add(new ServiceCall_Subject_I() { SubjectID = 2 });
ServiceCall changedObject = changeTracker.GetChanges().SingleOrDefault();
ServiceCall updatedObject = ExampleService.UpdateServiceCall(changedObject).Result;
```

but it's didn't add parent id automatically i get db exception on forigen key
and only if i add it menually its works
```
serviceCall.ServiceCall_Subject_Is.Add(new ServiceCall_Subject_I() { 
ServiceCallID = serviceCall.ID,
SubjectID = 2 });
```
I saw that in your examples you also add the father id to the child is it not better to do it automatically ? is it possible?

thanks

**Comment by tonysneed** [comment]
It’s by design that you need to add the parent first, because of how EF deals with updates in M-1 relations.
