### ISSUE TITLE
Index out of range exception @ ApplyChangesOnCollectionProperties

### ISSUE THREAD

**Issue by trucksmart** [TrackableEntities/trackable-entities#81]
I tried to attach the debugging symbol to investigate myself but couldn't:

For some reason when I try to use the `ApplyChanges` extension method I receive an index out of range exception @ `ApplyChangesOnCollectionProperties`.  I have generated client and service entities using the Code First approach.  I can update an entity successfully if I don't touch any relationship properties but as soon as I do I get the exception.  My entities are pretty simple:

**Service Entities**

    public class Vehicle : ITrackable, IMergeable
    {
        public Vehicle()
        {
            this.VehiclePictures = new List<VehiclePicture>();
        }

        public int Id { get; set; }
        public List<VehiclePicture> VehiclePictures { get; set; }
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        public Guid EntityIdentifier { get; set; }
    }

    public class VehiclePicture : ITrackable, IMergeable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int VehicleId { get; set; }
        public Vehicle Vehicle { get; set; }
        public TrackingState TrackingState { get; set; }
        public ICollection<string> ModifiedProperties { get; set; }
        public Guid EntityIdentifier { get; set; }
    }

**Client Entities**
Inherit EntityBase etc.

**Versions**
Trackable Entities 2.5.2
Entity Framework 6.1.3
ASP.NET MVC 5 w/ .NET 4.5
JSON .NET 7.0.1

**Comment by tonysneed** [comment]
For directions on debugging, see this page:
http://tonysneed.github.io/trackable-entities/5-debugging.html

Please let me know if this helps.

**Comment by trucksmart** [comment]
Tony,

Thank you for the quick reply.  The issue is shown with an arrow:

    private static void ApplyChangesOnCollectionProperties(TrackingState stateFilter, bool includeState,
        EntityNavigationProperty navProp, EntityCollectionProperty<IList> colProp,
        DbContext context, ITrackable item, ObjectVisitationHelper visitationHelper, TrackingState? state = null)
    {
        // Apply changes to 1-M and M-M properties filtering by tracking state
        var count = colProp.EntityCollection.Count;
        for (int i = count - 1; i > -1; i--)
        {
            var trackableChild = colProp.EntityCollection[i] as ITrackable; **< RIGHT HERE**
            if (trackableChild != null)
            {
                bool condition = includeState
                    ? trackableChild.TrackingState == stateFilter
                    : trackableChild.TrackingState != stateFilter;
                if (condition)
                    context.ApplyChanges(trackableChild, item, visitationHelper, navProp.Property.Name, state);                    
            } 
        }
    }

where `i` is `0` but throwing an IndexOutOfRangeException.

**Comment by trucksmart** [comment]
After more investigating `colProp.EntityCollection` is empty after the call to `context.ApplyChanges(trackableChild, item, visitationHelper, navProp.Property.Name, state);`.  This is why I am getting an IndexOutOfRangeException because the index `0` no longer exists.

**Comment by tonysneed** [comment]
Hello @trucksmart,

Sorry it's taken me this long to respond.  Ben underwater and am now just coming up for air.  Were you able to make any progress on this issue in the meantime?  If not, would you be able to create a failing test and submit a pull request?  That would help me replicate the error.  Thanks in advance.

Tony

**Comment by tonysneed** [comment]
I think what I need in order to replicate your scenario would be the state of entities: Unchanged, Added, Modified or Deleted.
